/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

uint32_t diff = 0;
uint32_t prev = 0;
uint32_t curr = 0;
float frequency = 0;

volatile uint32_t seconds = 0;
volatile uint8_t state = 0; // 0=100Hz, 1=1kHz, 2=2kHz

int main(void)
{
	//PWM GENERATION TIM4

	//Clock on GPIOD
 	uint32_t *clockregD = (uint32_t*)0x40023830;
	uint32_t *moderregD = (uint32_t*)0x40020C00;
	uint32_t *alt_fn_afhrD = (uint32_t*)0x40020C24;
	//enable TIM4
	uint32_t *RCC_APB1 = (uint32_t*)0x40023840;

	//counter enable
	uint32_t *control_tim1 = (uint32_t*)0x40000800;
	//uint32_t *status_register = (uint32_t*)0x40000810;
	uint32_t *prescalar = (uint32_t*)0x40000828;
	uint32_t *ARR = (uint32_t*)0x4000082C;

	*clockregD |=(1<<3);
	*RCC_APB1 |= (1<<2);

	*moderregD &=~(1<<24);
	*moderregD |=(1<<25);

	*alt_fn_afhrD &= ~(0xF << 16);
	*alt_fn_afhrD &=~(1<<19);
	*alt_fn_afhrD &=~(1<<18);
	*alt_fn_afhrD |=(1<<17);
	*alt_fn_afhrD &=~(1<<16);

	//ccmr // pwm mode
	uint32_t *tim4_ccmr = (uint32_t*)0x40000818;
	*tim4_ccmr &= ~(7<<4);
	*tim4_ccmr |=(1<<6);//1 ==> OCxM
	*tim4_ccmr |=(1<<5);//1 ==> OCxM
	*tim4_ccmr &=~(1<<4);//0 ==> OCxM

	*tim4_ccmr |=(1<<3);//preload enable ==> OC1PE
	*control_tim1 |=(1<<7); //APRE
	//CCER ===> ENABLE OUTPUT ON CHANNEL 1 //active high or low
	uint32_t *tim4_ccer = (uint32_t*)0x40000820;
	*tim4_ccer |=(1<<0);//1 ==> OCx

	//UG
	uint32_t *tim4_egr = (uint32_t*)0x40000814;

	//CCR for brightness control - DUTY CYCLE
	uint32_t *tim4_ccr = (uint32_t*)0x40000834;


	*prescalar = 160-1;
	*ARR = 1000-1;
	*tim4_ccr = 500;//50% DUTY CYCLE

	*tim4_egr |=(1<<0);
	*control_tim1 |=(1<<0);

	//FREQ CAPTURE TIM2

    //pa0 clk
	uint32_t *clockregA = (uint32_t*)0x40023830;
	*clockregA |=(1<<0);

	//tim2 clk
	*RCC_APB1 |= (1<<0); //tim2 enable for push button

	uint32_t *moderregA = (uint32_t*)0x40020000;
	*moderregA &=~(3<<0);
	//Altenate fn mode
	*moderregA |=(1<<1);
    *moderregA &=~(1<<0);

    uint32_t *afrlA = (uint32_t*)0x40020020;
    *afrlA &=~(15<<0);
	*afrlA &=~(1<<3);
	*afrlA &=~(1<<2);
	*afrlA &=~(1<<1);
	*afrlA |=(1<<0);

    // pull-down input push button
    //uint32_t *pupdrA = (uint32_t*)0x4002000C;
   // *pupdrA &= ~(3<<0);
    //*pupdrA |=  (2<<0);

	uint32_t *tim2_cr = (uint32_t*)0x40000000;//tim2
	uint32_t *tim2_psc = (uint32_t*)0x40000028;

	*tim2_psc = 16 - 1;   // 16 MHz / 16 = 1 MHz 1 us

	uint32_t *tim2_egr = (uint32_t*)0x40000014;
	*tim2_egr |= (1<<0);

	uint32_t *TIM2_ARR = (uint32_t*)0x4000002C;
	*TIM2_ARR = 0xFFFFFFFF;   // max (32-bit timer)

	uint32_t *tim2_ccmr = (uint32_t*)0x40000018;//tim2 capture compare done1
	// configure channel1 for input
	*tim2_ccmr &= ~(3<<0);   // clear CC1S bits
	*tim2_ccmr |=(1<<0);

	// filter  1111: fSAMPLING=fDTS/16, N=6
	*tim2_ccmr &= ~(15<<4);
	//*tim2_ccmr |= (1<<7);
	//*tim2_ccmr |= (1<<6);
	//*tim2_ccmr |= (1<<5);
	//*tim2_ccmr |= (1<<4);

	uint32_t *tim2_ccer = (uint32_t*)0x40000020;//tim2 capture compare enable
	//capture on rising edge
	*tim2_ccer &=~(1<<1);//cc1p done2

	*tim2_ccer |= (1<<0);   // CC1E enable ---> Here only capturing is start

	*tim2_cr |=(1<<0);//counter enable

	uint32_t *tim2_sr   = (uint32_t*)0x40000010;
	uint32_t *tim2_ccr1 = (uint32_t*)0x40000034;

	// tim5 SETTINGS FOR 1 SECOND
	*RCC_APB1 |= (1<<3); // TIM5 ENABLE
    uint32_t *TIM5_CR1  = (uint32_t*)0x40000C00;
    uint32_t *TIM5_PSC  = (uint32_t*)0x40000C28;
    uint32_t *TIM5_ARR  = (uint32_t*)0x40000C2C;
    uint32_t *TIM5_SR   = (uint32_t*)0x40000C10;

    *TIM5_PSC = 16000-1; // 16MHz → 1kHz
    *TIM5_ARR = 1000-1;  // 1 second

    *TIM5_CR1 |= (1<<0);


    while(1)
    {
        // -------- CAPTURE (continuous) -------- //
        if(*tim2_sr & (1<<1))
        {
            curr = *tim2_ccr1;

            if(curr >= prev)
                diff = curr - prev;
            else
                diff = (0xFFFFFFFF - prev + 1) + curr;

            prev = curr;

            frequency = 1000000.0 / diff;

            *tim2_sr &= ~(1<<1);
        }

        // -------- NON-BLOCKING 1 SECOND -------- //
        if(*TIM5_SR & (1<<0)) // update event
        {
            *TIM5_SR &= ~(1<<0);
            seconds++;

            if(seconds >= 10)
            {
                seconds = 0;

                state++;

                if(state == 1)
                {
                    *ARR = 100-1;   // 1 kHz
                    *tim4_ccr = 50;
                }
                else if(state == 2)
                {
                	 *ARR = 50-1;    // 2 kHz
                    *tim4_ccr = 25;
                }
                else
                {
                    state = 0;
                    *ARR = 1000-1;  // back to 100 Hz
                    *tim4_ccr = 500;
                }

                *tim4_egr |= (1<<0);
            }
        }
    }


}
