/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>


int main(void)
{
    uint32_t *clockreg = (uint32_t*)0x40023830;
    uint32_t *moderreg = (uint32_t*)0x40020C00;
	uint32_t *odrreg =(uint32_t*)0x40020C14;
	*clockreg |=(1<<3);

	*moderreg |=(1<<30);
	*moderreg &=~(1<<31);

	*moderreg |=(1<<28);
	*moderreg &=~(1<<29);

	*moderreg |=(1<<26);
	*moderreg &=~(1<<27);

	*moderreg |=(1<<24);
	*moderreg &=~(1<<25);

	/* Loop forever */
	for(;;)
	{

		*odrreg|=(1<<12);
		for(uint32_t i=0;i<200000;i++);
		*odrreg&=~(1<<12);
		for(uint32_t i=0;i<200000;i++);

		*odrreg|=(1<<13);
		for(uint32_t i=0;i<200000;i++);
		*odrreg&=~(1<<13);
		for(uint32_t i=0;i<200000;i++);

		*odrreg|=(1<<14);
		for(uint32_t i=0;i<200000;i++);
		*odrreg&=~(1<<14);
		for(uint32_t i=0;i<200000;i++);

		*odrreg|=(1<<15);
		for(uint32_t i=0;i<200000;i++);
		*odrreg&=~(1<<15);
		for(uint32_t i=0;i<200000;i++);




		*odrreg|=(1<<14);
		for(uint32_t i=0;i<200000;i++);
		*odrreg&=~(1<<14);
		for(uint32_t i=0;i<200000;i++);

		*odrreg|=(1<<13);
		for(uint32_t i=0;i<200000;i++);
		*odrreg&=~(1<<13);
		for(uint32_t i=0;i<200000;i++);

		*odrreg|=(1<<12);
		for(uint32_t i=0;i<200000;i++);
		*odrreg&=~(1<<12);
		for(uint32_t i=0;i<200000;i++);


	}

}
