/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

void ms_delay_tim(uint32_t n){
	uint32_t *rcc_cr = (uint32_t*)0x40023800;
	uint32_t *rcc_cfgr = (uint32_t*)0x40023808;
	uint32_t *control_tim1 = (uint32_t*)0x40000000;
	uint32_t *status_register = (uint32_t*)0x40000010;
	uint32_t *prescalar = (uint32_t*)0x40000028;
	uint32_t *ARR = (uint32_t*)0x4000002C;

	uint32_t *RCC_APB1 = (uint32_t*)0x40023840;
	*rcc_cr |= (1<<16);
	while(!(*rcc_cr & (1<<17)));

	*rcc_cfgr |= (1<<0);
	*rcc_cfgr &= ~(1<<1);
	while ( (*rcc_cfgr & ((1<<3) | (1<<2))) != (1<<2) );

	*RCC_APB1 |= (1<<0);

	*prescalar = 8000-1;
	*ARR = 1000-1;
	*control_tim1 |=(1<<0);

	for(uint32_t i=0;i<n;i++){
		while(!(*status_register & (1<<0)));
		*status_register &= ~(1<<0);
	}

}
int main(void)
{
	 uint32_t *clockregD = (uint32_t*)0x40023830;
	 uint32_t *moderregD = (uint32_t*)0x40020C00;
     uint32_t *odrregD = (uint32_t*)0x40020C14;
	*clockregD |=(1<<3);

	*moderregD |=(1<<24);
	*moderregD &=~(1<<25);



    /* Loop forever */
	for(;;){
	    *odrregD|=(1<<12);
	    ms_delay_tim(5);

	    *odrregD&=~(1<<12);
	    ms_delay_tim(2);

	}

}
