/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

uint32_t new = 0;

int main(void)
{
	uint32_t *RCC_AHB1 = (uint32_t*)0x40023830;
	*RCC_AHB1 |=(1<<0);

	uint32_t *RCC_APB2 = (uint32_t*)0x40023844;
	*RCC_APB2 |=(1<<8);

	// SET PA0 IN ANALOG MODE
	uint32_t *moderregA = (uint32_t*)0x40020000;
	 *moderregA |= (1<<0);
	 *moderregA |= (1<<1);

    uint32_t *Adc1_sqr1 = (uint32_t*)0x4001202C;
    // No of conversions = 1 // L = 0000
    *Adc1_sqr1 &=~ (1<<20);
    *Adc1_sqr1 &=~ (1<<21);
    *Adc1_sqr1 &=~ (1<<22);
    *Adc1_sqr1 &=~ (1<<23);

	uint32_t *Adc1_sqr3 = (uint32_t*)0x40012034;
	// Selecting channel 0 00000
	*Adc1_sqr3 &=~ (1<<4);
	*Adc1_sqr3 &=~ (1<<3);
	*Adc1_sqr3 &=~ (1<<2);
	*Adc1_sqr3 &=~ (1<<1);
	*Adc1_sqr3 &=~ (1<<0);

	uint32_t *Adc1_smpr2 = (uint32_t*)0x40012010;
	*Adc1_smpr2 &= ~(7 << 0);
	*Adc1_smpr2 |= (1<<0);
	*Adc1_smpr2 |= (1<<1);
	*Adc1_smpr2 |= (1<<2);

	uint32_t *Adc1_ctrl2 = (uint32_t*)0x40012008;

	//ADON
	*Adc1_ctrl2 |= (1<<0);
    for(volatile int i=0; i<10000; i++);

	//Align bit = 0 for right alignment of converted bits
	*Adc1_ctrl2 &=~ (1<<11);

	uint32_t *Adc1_SR = (uint32_t*)0x40012000;
	uint32_t *Adc1_DR = (uint32_t*)0x4001204C;

	while(1){
		//swstart
		*Adc1_ctrl2 |= (1<<30);

		while(!(*Adc1_SR & (1<<1)));

		new = *Adc1_DR;

	    for(volatile int i=0; i<10000; i++);

	}

}
