/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

volatile uint32_t diff = 0;
volatile uint32_t prev = 0;
volatile uint32_t curr = 0;
volatile float frequency = 0;
volatile float rpm = 0;
volatile float test = 0;
volatile uint32_t capture_count = 0;

int main(void)
{
    //pa0 clk
	uint32_t *clockregA = (uint32_t*)0x40023830;
	*clockregA |=(1<<0);

	//tim2 clk
	uint32_t *RCC_APB1 = (uint32_t*)0x40023840;
	*RCC_APB1 |= (1<<0); //tim2 enable for push button

	uint32_t *moderregA = (uint32_t*)0x40020000;
	*moderregA &=~(3<<0);
	//Altenate fn mode
	*moderregA |=(1<<1);
    *moderregA &=~(1<<0);

    uint32_t *afrlA = (uint32_t*)0x40020020;
    *afrlA &=~(15<<0);

	*afrlA |=(1<<0);

    // pull-down input push button
    uint32_t *pupdrA = (uint32_t*)0x4002000C;
    *pupdrA &= ~(3<<0);
    *pupdrA |=  (2<<0);

	uint32_t *tim2_cr = (uint32_t*)0x40000000;//tim2
	uint32_t *tim2_psc = (uint32_t*)0x40000028;

  	*tim2_psc = 16000 - 1;   // 16 MHz / 16000 = 1 KHz 1 ms

	uint32_t *tim2_egr = (uint32_t*)0x40000014;
	*tim2_egr |= (1<<0);

	uint32_t *TIM2_ARR = (uint32_t*)0x4000002C;
	*TIM2_ARR = 0xFFFFFFFF;   // max (32-bit timer)

	uint32_t *tim2_ccmr = (uint32_t*)0x40000018;//tim2 capture compare done1
	// configure channel1 for input
	*tim2_ccmr &= ~(3<<0);   // clear CC1S bits
	*tim2_ccmr |=(1<<0);

	// filter  1111: fSAMPLING=fDTS/16, N=6
	*tim2_ccmr &= ~(15<<4);
	//*tim2_ccmr |= (1<<7);
	//*tim2_ccmr |= (1<<6);
	//*tim2_ccmr |= (1<<5);
	//*tim2_ccmr |= (1<<4);

	uint32_t *tim2_ccer = (uint32_t*)0x40000020;//tim2 capture compare enable
	//capture on rising edge
	*tim2_ccer &=~(1<<1);//cc1p done2

	*tim2_ccer |= (1<<0);   // CC1E enable ---> Here only capturing is start

	*tim2_cr |=(1<<0);//counter enable

	uint32_t *tim2_sr   = (uint32_t*)0x40000010;
	uint32_t *tim2_ccr1 = (uint32_t*)0x40000034;

	while(1)
	{
  	    if(*tim2_sr & (1<<1))   // CC1IF
	    {
  	    	capture_count++;
	        curr = *tim2_ccr1;

	        if(curr >= prev)
	            diff = curr - prev;
	        else
	            diff = (0xFFFFFFFF - prev) + curr;

	        prev = curr;

	        // Timer clock = 1 MHz
	        if(diff > 0)
	        {
	           frequency = 1000.0 / diff;
	            rpm = (frequency * 60.0f) / 20.0f;
	            test = rpm * 100;
	        }

	        //frequency = 10;
	        //rpm = (frequency * 60.0f) / 20.0f;
	        //test = rpm * 100;

	        *tim2_sr = 0;

	       // *tim2_sr &= ~(1<<1);   // clear flag
	    }
	}

}
