/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>


int main(void)
{
	//Clock on GPIOD
	uint32_t *clockregD = (uint32_t*)0x40023830;
	uint32_t *moderregD = (uint32_t*)0x40020C00;
	uint32_t *alt_fn_afhrD = (uint32_t*)0x40020C24;
	//enable TIM4
	uint32_t *RCC_APB1 = (uint32_t*)0x40023840;

	//counter enable
	uint32_t *control_tim1 = (uint32_t*)0x40000800;
	//uint32_t *status_register = (uint32_t*)0x40000810;
	uint32_t *prescalar = (uint32_t*)0x40000828;
	uint32_t *ARR = (uint32_t*)0x4000082C;

	*clockregD |=(1<<3);
	*RCC_APB1 |= (1<<2);

	*moderregD &=~(1<<24);
	*moderregD |=(1<<25);

	*alt_fn_afhrD &=~(1<<19);
	*alt_fn_afhrD &=~(1<<18);
	*alt_fn_afhrD |=(1<<17);
	*alt_fn_afhrD &=~(1<<16);

	//ccmr // pwm mode
	uint32_t *tim4_ccmr = (uint32_t*)0x40000818;
	*tim4_ccmr |=(1<<6);//1 ==> OCxM
	*tim4_ccmr |=(1<<5);//1 ==> OCxM
	*tim4_ccmr &=~(1<<4);//0 ==> OCxM

	*tim4_ccmr |=(1<<3);//preload enable ==> OC1PE
	*control_tim1 |=(1<<7); //APRE
	//CCER ===> ENABLE OUTPUT ON CHANNEL 1 //active high or low
	uint32_t *tim4_ccer = (uint32_t*)0x40000820;
	*tim4_ccer |=(1<<0);//1 ==> OCx

	//UG
	uint32_t *tim4_egr = (uint32_t*)0x40000814;

	//CCR for brightness control - DUTY CYCLE
	uint32_t *tim4_ccr = (uint32_t*)0x40000834;


	*prescalar = 160-1;
	*ARR = 1000-1;
	*tim4_ccr = 100;

	*tim4_egr |=(1<<0);
	*control_tim1 |=(1<<0);


}
