/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

int main(void)
{
	 uint32_t *clockreg = (uint32_t*)0x40023830;
	 uint32_t *moderreg = (uint32_t*)0x40020800;
	 uint32_t *odrreg =(uint32_t*)0x40020814;

	 *clockreg |=(1<<2);

	 *moderreg |=(1<<12);
	 *moderreg &=~(1<<13);
    /* Loop forever */
	for(;;)
	{
		*odrreg|=0x0040;
		for(uint32_t i=0;i<200000;i++);
		*odrreg&=~0x0040;
		for(uint32_t i=0;i<200000;i++);
	}
}
