/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

int main(void)
{
	uint32_t *clockregA = (uint32_t*)0x40023830;
	//uint32_t clockregD = (uint32_t)0x40023830;
	uint32_t *moderregA = (uint32_t*)0x40020000;
	uint32_t *moderregD = (uint32_t*)0x40020C00;
	uint32_t *idrregA =(uint32_t*)0x40020010;
	uint32_t *odrregD =(uint32_t*)0x40020C14;


	*clockregA |=(1<<0);
	*clockregA |=(1<<3);

	 //*moderregA &=~(1<<0);
	 //*moderregA &=~(1<<1);

	//above 2 lines can also be written as
	*moderregA &=~(3<<0);

	 *moderregD |=(1<<24);
	 *moderregD &=~(1<<25);
   for(;;){
	 if(*idrregA & (1 << 0))
	 {
		 *odrregD|=0x00001000;
	 }
	 else
	 {
		 *odrregD&=~0x00001000;
	 }

   }

}


